apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dev-station-ingress
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.host }}`)
      services:
        - kind: Service
          name: {{ .Values.ingress.service.name }}
          port: {{ .Values.container.port }}