apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer-role
  namespace: {{ .Release.Namespace }}
rules:
  # select your needed api groups
- apiGroups: ["", "apps", batch", "networking.k8s.io", "networking", "extensions", "traefik.io"]
  # select your needed resources
  # don't forget the according apiGroup above
  resources: [ "deployments", "pods", "replicasets", "services", "configmaps", "persistentvolumeclaims", "secrets", "IngressRoute"]
  # select your needed permissions (keep to a minimum)
  verbs: [ "create", "get", "list", "delete", "watch", "update", "patch"]
