apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-service
  namespace: { .Release.Namespace }
spec:
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .Values.container.port }}
  type: ClusterIP
