apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dev-station-gitea-ingress
  namespace: dev-station
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`dev-station.cluster.sololab.one`) && PathPrefix(`/gitea`)
      middlewares: 
      - name: gitea-rewrite
        namespace: dev-station
      services:
        - kind: Service
          name: gitea-http
          port: 3000