image:
  repository: sololaboratories/dev-station
  tag: prototype
  pullPolicy: Always

container:
  name: web-container
  port: 8080

pvc:
  size: 1Gi

deployment:
  name: web-deployment

serviceAccount:
  name: deployer

ingress:
  host: dev-station.cluster.sololab.one
  service: 
    name: web-deployment-service
